In [1]:
import pandas as pd
import numpy as np

https://servicos.receita.fazenda.gov.br/publico/EstatisticaIRPF/estatisticasDIRPF_UF_2024.HTML

In [30]:
url = "https://servicos.receita.fazenda.gov.br/publico/EstatisticaIRPF/estatisticasDIRPF_2024.CSV"
arq = "estatisticas-dirpf-2024.csv"

!test -f $arq || !wget -O $arq $url
!ls -lah $arq

-rw-r--r-- 1 s033236209 domain users 570K jun  1 08:06 estatisticas-dirpf-2024.csv

In [31]:
!head $arq

In [32]:
df = pd.read_csv(arq, sep=';', encoding='iso-8859-1')
df

,UF,Município,Ano 2024,Completa,Simplificada,Original,Retificadora,IAP,IAR,SSI,...,Online,Restituição Conta,Restituição PIX,Final Espólio,Saída Definitiva,Feminino,Média Idade,Ano 2023,Ano 2022,Ano 2021
0,AC,ACRELANDIA,1.039,337,702,967,72.0,231.0,609,199.0,...,124.0,435,174.000,0.0,1.0,492,44,956,833,774
1,AC,ASSIS BRASIL,622,168,454,576,46.0,124.0,426,72.0,...,95.0,279,147.000,0.0,0.0,304,44,594,515,530
2,AC,BRASILEIA,2.623,823,1.800,2.447,176.0,551.0,1.673,399.0,...,188.0,884,789.000,0.0,0.0,1.220,46,2.607,2.217,2.000
3,AC,BUJARI,743,278,465,705,38.0,145.0,499,99.0,...,90.0,232,267.000,0.0,0.0,385,45,700,625,551
4,AC,CAPIXABA,652,169,483,600,52.0,126.0,400,126.0,...,36.0,241,159.000,0.0,0.0,329,45,590,473,387
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5566,TO,TOCANTINOPOLIS,3.130,1.251,1.879,2.814,316.0,328.0,2.420,382.0,...,270.0,1.391,1.029,1.0,0.0,1.433,46,2.846,2.404,2.340
5567,TO,TUPIRAMA,246,101,145,234,12.0,24.0,191,31.0,...,24.0,107,84.000,0.0,0.0,99,43,219,193,171
5568,TO,TUPIRATINS,173,63,110,150,23.0,27.0,127,19.0,...,14.0,62,65.000,0.0,0.0,99,46,150,135,123
5569,TO,WANDERLANDIA,811,293,518,755,56.0,110.0,570,131.0,...,69.0,328,242.000,0.0,0.0,430,45,724,617,555
5570,TO,XAMBIOA,1.485,606,879,1.359,126.0,282.0,983,220.0,...,186.0,562,421.000,0.0,0.0,551,43,1.364,1.074,1.025

In [33]:
dfd = df[['UF', 'Município', 'Ano 2021', 'Ano 2022', 'Ano 2023', 'Ano 2024']].copy()
#dfd

In [34]:
dfd = df[['UF', 'Município', 'Ano 2021', 'Ano 2022', 'Ano 2023', 'Ano 2024']].copy()
for c in dfd.columns:
    if c.startswith('Ano'):
        ano = c.split(' ')[-1]
        dfd.rename({c: ano}, inplace=True, axis=1)
        dfd[ano] = dfd[ano].apply(lambda x: int(x.replace('.', '')))
dfd

      UF       Município  2021  2022  2023  2024
0     AC      ACRELANDIA   774   833   956  1039
1     AC    ASSIS BRASIL   530   515   594   622
2     AC       BRASILEIA  2000  2217  2607  2623
3     AC          BUJARI   551   625   700   743
4     AC        CAPIXABA   387   473   590   652
...   ..             ...   ...   ...   ...   ...
5566  TO  TOCANTINOPOLIS  2340  2404  2846  3130
5567  TO        TUPIRAMA   171   193   219   246
5568  TO      TUPIRATINS   123   135   150   173
5569  TO    WANDERLANDIA   555   617   724   811
5570  TO         XAMBIOA  1025  1074  1364  1485

[5571 rows x 6 columns]

In [41]:
csv = 'entregas-dirpf-2021-2024.csv'
dfd.to_csv(csv, index=False)

In [42]:
!head $csv && tail $csv

UF,Município,2021,2022,2023,2024
AC,ACRELANDIA,774,833,956,1039
AC,ASSIS BRASIL,530,515,594,622
AC,BRASILEIA,2000,2217,2607,2623
AC,BUJARI,551,625,700,743
AC,CAPIXABA,387,473,590,652
AC,CRUZEIRO DO SUL,8151,9083,10659,11171
AC,EPITACIOLANDIA,1336,1571,1711,1764
AC,FEIJO,1533,1839,1936,2107
AC,JORDAO,168,386,332,354
TO,SUCUPIRA,94,95,135,161
TO,TAGUATINGA,865,875,1120,1293
TO,TAIPAS DO TOCANTINS,91,129,152,180
TO,TALISMA,200,231,318,331
TO,TOCANTINIA,411,444,564,606
TO,TOCANTINOPOLIS,2340,2404,2846,3130
TO,TUPIRAMA,171,193,219,246
TO,TUPIRATINS,123,135,150,173
TO,WANDERLANDIA,555,617,724,811
TO,XAMBIOA,1025,1074,1364,1485