In [1]:
import pandas as pd
import numpy as np

https://servicos.receita.fazenda.gov.br/publico/EstatisticaIRPF/estatisticasDIRPF_UF_2024.HTML

In [2]:
ano = 2021
url = "https://servicos.receita.fazenda.gov.br/publico/EstatisticaIRPF/estatisticasDIRPF_%d.CSV" % ano
arq = "estatisticas-dirpf-%d.csv" % ano

!test -f $arq || wget -O $arq $url
!ls -lah $arq

-rw-r--r-- 1 s033236209 domain users 524K jun  8 00:51 estatisticas-dirpf-2021.csv

In [3]:
!head $arq

In [4]:
df = pd.read_csv(arq, sep=';', encoding='iso-8859-1')
df

,UF,Município,Ano 2021,Completa,Simplificada,Original,Retificadora,IAP,IAR,SSI,...,Online,Restituição Conta,Restituição PIX,Final Espólio,Saída Definitiva,Feminino,Média Idade,Ano 2020,Ano 2019,Ano 2018
0,AC,ACRELANDIA,774,250,524,660,114.0,170.0,410,194,...,3.0,410,0,0.0,0.0,339,44,708,694,651
1,AC,ASSIS BRASIL,530,174,356,468,62.0,116.0,311,103,...,1.0,311,0,0.0,0.0,251,43,447,433,425
2,AC,BRASILEIA,2.000,711,1.289,1.771,229.0,425.0,1.119,456,...,3.0,1.119,0,0.0,0.0,927,46,1.771,1.802,1.618
3,AC,BUJARI,551,220,331,482,69.0,117.0,340,94,...,2.0,340,0,0.0,0.0,259,45,512,485,417
4,AC,CAPIXABA,387,102,285,355,32.0,89.0,209,89,...,0.0,209,0,0.0,0.0,177,45,352,335,311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5566,TO,TOCANTINOPOLIS,2.340,1.058,1.282,2.023,317.0,297.0,1.673,370,...,5.0,1.673,0,0.0,0.0,1.048,47,2.125,2.052,1.945
5567,TO,TUPIRAMA,171,62,109,157,14.0,14.0,105,52,...,0.0,105,0,0.0,0.0,48,43,153,168,163
5568,TO,TUPIRATINS,123,41,82,111,12.0,19.0,73,31,...,0.0,73,0,0.0,0.0,68,48,102,101,94
5569,TO,WANDERLANDIA,555,224,331,450,105.0,80.0,357,118,...,0.0,357,0,0.0,0.0,266,47,527,484,511
5570,TO,XAMBIOA,1.025,433,592,888,137.0,166.0,630,229,...,2.0,630,0,0.0,2.0,418,44,893,828,825

In [5]:
dfd = df[['UF', 'Município',
          'Ano %d' % (ano - 3),
          'Ano %d' % (ano - 2),
          'Ano %d' % (ano - 1),
          'Ano %d' % ano]].copy()
dfd.rename({'UF': 'uf', 'Município': 'municipio'}, axis=1, inplace=True)
for c in dfd.columns:
    if c.startswith('Ano'):
        nano = "d" + c.split(' ')[-1]
        dfd.rename({c: nano}, inplace=True, axis=1)
        dfd[nano] = dfd[nano].apply(lambda x: int(x.replace('.', '')))
dfd

      uf       municipio  d2018  d2019  d2020  d2021
0     AC      ACRELANDIA    651    694    708    774
1     AC    ASSIS BRASIL    425    433    447    530
2     AC       BRASILEIA   1618   1802   1771   2000
3     AC          BUJARI    417    485    512    551
4     AC        CAPIXABA    311    335    352    387
...   ..             ...    ...    ...    ...    ...
5566  TO  TOCANTINOPOLIS   1945   2052   2125   2340
5567  TO        TUPIRAMA    163    168    153    171
5568  TO      TUPIRATINS     94    101    102    123
5569  TO    WANDERLANDIA    511    484    527    555
5570  TO         XAMBIOA    825    828    893   1025

[5571 rows x 6 columns]

In [6]:
csv = 'declaracoes-%d.csv' % ano
print(csv)
dfd.to_csv(csv, index=False)

declaracoes-2021.csv

In [7]:
!head $csv && tail $csv

uf,municipio,d2018,d2019,d2020,d2021
AC,ACRELANDIA,651,694,708,774
AC,ASSIS BRASIL,425,433,447,530
AC,BRASILEIA,1618,1802,1771,2000
AC,BUJARI,417,485,512,551
AC,CAPIXABA,311,335,352,387
AC,CRUZEIRO DO SUL,6726,7088,7543,8151
AC,EPITACIOLANDIA,1063,1139,1229,1336
AC,FEIJO,1200,1315,1494,1533
AC,JORDAO,130,153,155,168
TO,SUCUPIRA,80,105,97,94
TO,TAGUATINGA,696,724,748,865
TO,TAIPAS DO TOCANTINS,53,63,88,91
TO,TALISMA,136,159,167,200
TO,TOCANTINIA,329,375,385,411
TO,TOCANTINOPOLIS,1945,2052,2125,2340
TO,TUPIRAMA,163,168,153,171
TO,TUPIRATINS,94,101,102,123
TO,WANDERLANDIA,511,484,527,555
TO,XAMBIOA,825,828,893,1025